### ISSUE TITLE
output folder not found

### ISSUE THREAD

**Issue by megeshcorp** [teavanist/MNIST-JPG#2]
Hi,
I'm trying to use this file. I created the output folder in the same location as the file, but I get the following error :

runfile('C:/Users/Eshkar/MNIST/data/mnist_jpg.py', wdir='C:/Users/Eshkar/MNIST/data')
usage: C:/Users/Eshkar/MNIST/data/mnist_jpg.py <output_path>
Please create a folder named Output in the same location as the script
An exception has occurred, use %tb to see the full traceback.

SystemExit

**Full traceback** 

Traceback (most recent call last):

  File "<ipython-input-9-795fab3a0284>", line 1, in <module>
    runfile('C:/Users/Eshkar/MNIST/data/mnist_jpg.py', wdir='C:/Users/Eshkar/MNIST/data')

  File "C:\Users\Eshkar\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Eshkar\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Eshkar/MNIST/data/mnist_jpg.py", line 113, in <module>
    sys.exit()

SystemExit

**Comment by teavanist** [comment]
Hi @megeshcorp - Sorry for the delay. I had not been logging into Github for a long time and just saw this issue today. I havent worked on the code after I uploaded it to GitHub. Let me try it out this weekend and get back to you.

**Comment by teavanist** [comment]
@megeshcorp - Meanwhile, you can download the zip file. It contains all the images you will need in JPG format.

**Comment by teavanist** [comment]
Hi @megeshcorp  - I was not able to replicate this error at my end. The code worked fine. I suggest using the JPG files from the zip for your project.
